#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="${SCRIPT_DIR}/../docker-compose.yml"
DB_NAME="${DB_NAME:-domain_core}"
DB_USER="${DB_USER:-postgres}"

echo "WARNING: resetting the PostgreSQL container and volume defined by ${COMPOSE_FILE}."
echo "All existing data in this project database will be permanently removed."

echo "Stopping and removing the current PostgreSQL container and volume..."
docker compose -f "${COMPOSE_FILE}" down --volumes --remove-orphans

echo "Starting a fresh PostgreSQL instance from ${COMPOSE_FILE}..."
docker compose -f "${COMPOSE_FILE}" up -d postgres

echo "Waiting for PostgreSQL to become ready..."
until docker compose -f "${COMPOSE_FILE}" exec -T postgres pg_isready -U "${DB_USER}" -d "${DB_NAME}" >/dev/null 2>&1; do
  sleep 2
done

echo "Creating the application schema in the fresh database..."
docker compose -f "${COMPOSE_FILE}" exec -T postgres \
  psql -v ON_ERROR_STOP=1 -U "${DB_USER}" -d "${DB_NAME}" <<'SQL'
CREATE TABLE IF NOT EXISTS domain (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  status BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "option" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  status BOOLEAN NOT NULL,
  "values" JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS attribute (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  status BOOLEAN NOT NULL,
  type VARCHAR(255) NOT NULL,
  mandatory BOOLEAN NOT NULL,
  domain_id BIGINT NOT NULL REFERENCES domain(id),
  option_id BIGINT REFERENCES "option"(id)
);

CREATE TABLE IF NOT EXISTS domain_relation (
  domain_id BIGINT NOT NULL REFERENCES domain(id),
  related_domain_id BIGINT NOT NULL REFERENCES domain(id),
  CONSTRAINT domain_relation_pk PRIMARY KEY (domain_id, related_domain_id),
  CONSTRAINT domain_relation_not_self CHECK (domain_id <> related_domain_id)
);
SQL

DOMAIN_TABLE_EXISTS="$(docker compose -f "${COMPOSE_FILE}" exec -T postgres \
  psql -At -U "${DB_USER}" -d "${DB_NAME}" \
  -c "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'domain');" | tr -d '\r')"
if [[ "${DOMAIN_TABLE_EXISTS}" != "t" ]]; then
  cat >&2 <<'MESSAGE'
The PostgreSQL schema is not initialized: table public.domain was not found.
The schema bootstrap failed. Check the PostgreSQL container and the database configuration:
  DB_URL=jdbc:postgresql://localhost:5432/domain_core
  DB_USERNAME=postgres
  DB_PASSWORD=postgres
MESSAGE
  exit 1
fi

echo "Loading domains, options and attributes..."
docker compose -f "${COMPOSE_FILE}" exec -T postgres \
  psql -v ON_ERROR_STOP=1 -U "${DB_USER}" -d "${DB_NAME}" \
  < "${SCRIPT_DIR}/domain_load.sql"

echo "Load completed successfully."
